Issue#7
oscarzhpersson/DD2480_Lab1-Decide pull request #20
Opened 2022-01-30 13:51 UTC by mustafamusse

2022-01-30 13:52 UTC, oscarzhpersson requested changes
This is quite good, but please change the summary a bit. It's supposed to be shorter and descriptive of the function. Currently the text is copied from the assignment, but it's better if it's written in our own words from what it does.

2022-01-30 13:59 UTC, oscarzhpersson commented
I would also look over the commit structure as well. At least for the next issue you do

2022-02-01 13:19 UTC, tim-jonsson approved these changes

2022-02-01 13:22 UTC, oscarzhpersson approved these changes
Requested changes have been sufficiently amended

2022-02-01 13:22 UTC, merged